"""Packaging contracts; no downloads or native compiler required."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile
import tomllib
import unittest

ROOT = Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location('bootstrap', ROOT / 'scripts/bootstrap-native.py')
bootstrap = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bootstrap)
spec = importlib.util.spec_from_file_location('install_observer', ROOT / 'scripts/install-observer.py')
install_observer = importlib.util.module_from_spec(spec)
spec.loader.exec_module(install_observer)
# observer/examples/connected_components/lemmalog_star.rs: the reference phase implementation.
REFERENCE_STAR_SHA256 = 'f3ce91b429dc6f8971a5f98e8f5c50b8b60921732c498b985ea07cc563117c0e'
GENERATED_PREAMBLE = '#![allow(dead_code)]\n// generated by ddlog\n'


class NativePackaging(unittest.TestCase):
    def test_corrupt_archive_is_rejected(self):
        with tempfile.TemporaryDirectory() as d:
            archive = Path(d) / 'archive'
            archive.write_bytes(b'original')
            digest = hashlib.sha256(archive.read_bytes()).hexdigest()
            bootstrap.verify_archive(archive, digest)
            archive.write_bytes(b'tampered')
            with self.assertRaisesRegex(ValueError, 'remove .* and retry'):
                bootstrap.verify_archive(archive, digest)

    def test_operator_and_plain_locks_pin_identical_external_dependencies(self):
        locks = [tomllib.loads((ROOT / 'native' / name).read_text())['package']
                 for name in ('program.Cargo.lock', 'star.Cargo.lock')]
        external = [[p for p in packages if 'source' in p] for packages in locks]
        self.assertEqual(external[0], external[1])
        for package in external[0]:
            if package['source'].startswith('git+'):
                self.assertRegex(package['source'], r'#[0-9a-f]{40}$')
            else:
                self.assertRegex(package['checksum'], r'^[0-9a-f]{64}$')

    def test_driver_selects_lock_and_preserves_explicit_override(self):
        for star, override in ((False, False), (True, False), (True, True)):
            with self.subTest(star=star, override=override), tempfile.TemporaryDirectory() as d:
                root = Path(d)
                (root / 'bin').mkdir()
                compiler = root / 'bin/ddlog'
                compiler.write_text('#!/bin/sh\nmkdir -p program_ddlog/.cargo\n' +
                                    ('mkdir -p program_ddlog/types/lemmalog_star\n' if star else ''))
                compiler.chmod(0o755)
                cargo = root / 'cargo'
                cargo.write_text('#!/bin/sh\nprintf "%s\\n" "$@" > args\nmkdir -p target/debug\nprintf binary > target/debug/program_cli\n')
                cargo.chmod(0o755)
                # Simulated pinned generator output needed by the native hook installer.
                project = root / 'program_ddlog'
                (project / 'differential_datalog/src/program').mkdir(parents=True)
                (project / 'src').mkdir()
                (project / 'differential_datalog/src/lib.rs').write_text('')
                (project / 'differential_datalog/src/program/worker.rs').write_text(
                    '            self.worker.log_register().remove("differential/arrange");\n        };\n        Ok(())')
                (project / 'src/main.rs').write_text('        differential_idle_merge_effort: args.idle_merge_effort,')
                (root / 'program.dl').write_text('fixture')
                # An explicit lock must name the star member when the program imports it.
                (root / 'override.lock').write_text('explicit override\n[[package]]\nname = "types__lemmalog_star"\n')
                env = {k: v for k, v in os.environ.items() if not k.startswith(('DDLOG_', 'CARGO_'))}
                env.update(DDLOG_HOME=str(root), DDLOG_CARGO=str(cargo), DDLOG_OFFLINE='1',
                           DDLOG_LOCK_DIR=str(ROOT / 'native'))
                if override:
                    env['DDLOG_CARGO_LOCK'] = str(root / 'override.lock')
                subprocess.run([str(ROOT / 'scripts/build-ddlog.sh'), str(root / 'program.dl'), str(root / 'output')],
                               env=env, check=True, capture_output=True)
                expected = root / 'override.lock' if override else ROOT / 'native' / ('star.Cargo.lock' if star else 'program.Cargo.lock')
                self.assertEqual((root / 'program_ddlog/Cargo.lock').read_bytes(), expected.read_bytes())
                self.assertIn('--locked', (root / 'program_ddlog/args').read_text())
                self.assertEqual((root / 'output').read_text(), 'binary')
                self.assertEqual((project / 'differential_datalog/src/observer.rs').read_bytes(), (ROOT / 'native/observer.rs').read_bytes())
                marker = json.loads((project / 'observer-install.json').read_text())
                self.assertEqual(marker['observer_hook'], True)
                self.assertEqual(marker['star_phases'], None)

    def test_driver_refuses_explicit_lock_without_star_member(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            (root / 'bin').mkdir()
            compiler = root / 'bin/ddlog'
            compiler.write_text('#!/bin/sh\nmkdir -p program_ddlog/.cargo program_ddlog/types/lemmalog_star\n')
            compiler.chmod(0o755)
            cargo = root / 'cargo'
            cargo.write_text('#!/bin/sh\nprintf "%s\\n" "$@" > args\n')
            cargo.chmod(0o755)
            project = root / 'program_ddlog'
            (project / 'differential_datalog/src/program').mkdir(parents=True)
            (project / 'src').mkdir()
            (project / 'differential_datalog/src/lib.rs').write_text('')
            (project / 'differential_datalog/src/program/worker.rs').write_text(
                '            self.worker.log_register().remove("differential/arrange");\n        };\n        Ok(())')
            (project / 'src/main.rs').write_text('        differential_idle_merge_effort: args.idle_merge_effort,')
            (root / 'program.dl').write_text('fixture')
            env = {k: v for k, v in os.environ.items() if not k.startswith(('DDLOG_', 'CARGO_'))}
            env.update(DDLOG_HOME=str(root), DDLOG_CARGO=str(cargo), DDLOG_OFFLINE='1',
                       DDLOG_LOCK_DIR=str(ROOT / 'native'), DDLOG_CARGO_LOCK=str(ROOT / 'native/program.Cargo.lock'))
            result = subprocess.run([str(ROOT / 'scripts/build-ddlog.sh'), str(root / 'program.dl'), str(root / 'output')],
                                    env=env, capture_output=True, text=True)
            self.assertEqual(result.returncode, 1, result.stderr)
            self.assertIn('does not lock types__lemmalog_star', result.stderr)
            self.assertIn('DDLOG_LOCK_DIR', result.stderr)
            self.assertFalse((project / 'Cargo.lock').exists())
            self.assertFalse((project / 'args').exists())

    def test_star_phases_patch_equals_reference_and_fails_closed(self):
        pinned = (ROOT / 'src/star/lemmalog_star.rs').read_text()
        patched = install_observer.patch_star(GENERATED_PREAMBLE + pinned)
        self.assertTrue(patched.startswith(GENERATED_PREAMBLE))
        body = patched[len(GENERATED_PREAMBLE):]
        self.assertEqual(hashlib.sha256(body.encode()).hexdigest(), REFERENCE_STAR_SHA256)
        for phase in ('large-star', 'small-star', 'minimum-label'):
            self.assertEqual(body.count(f'region_named("{phase}"'), 1)
        self.assertEqual(install_observer.patch_star(patched), patched)
        with self.assertRaisesRegex(ValueError, 'star large-star open'):
            install_observer.patch_star(pinned.replace('let large = symmetric', 'let large = other'))
        with self.assertRaisesRegex(ValueError, 'star'):
            install_observer.patch_star(pinned + pinned)
        with tempfile.TemporaryDirectory() as d:
            project = Path(d)
            (project / 'differential_datalog/src/program').mkdir(parents=True)
            (project / 'src').mkdir()
            (project / 'types/lemmalog_star').mkdir(parents=True)
            (project / 'differential_datalog/src/lib.rs').write_text('')
            (project / 'differential_datalog/src/program/worker.rs').write_text(install_observer.WORKER_SITE)
            (project / 'src/main.rs').write_text(install_observer.CLI_SITE)
            (project / 'types/lemmalog_star/lemmalog_star.rs').write_text(GENERATED_PREAMBLE + pinned)
            marker = install_observer.install(project)
            self.assertEqual(marker['star_phases'], True)
            self.assertEqual((project / 'types/lemmalog_star/lemmalog_star.rs').read_text(), patched)
            self.assertEqual(json.loads((project / 'observer-install.json').read_text()), marker)
            self.assertEqual(install_observer.install(project), marker)


if __name__ == '__main__':
    unittest.main()
